### ISSUE TITLE
ModuleNotFoundError: No module named 'tasks.rosvot.rosvot_utils'

### ISSUE THREAD

**Issue by fish0510** [RickyL-2000/ROSVOT#1]
Hello,

I encountered an issue while trying to run _inference/rosvot.py_. Specifically, I am getting the following error:
`ModuleNotFoundError: No module named 'tasks.rosvot.rosvot_utils'`
I think there are some missing codes in the repo.

Thank you for your assistance.

**Comment by RickyL-2000** [comment]
Thanks. I think the problem is fixed now.
