### ISSUE TITLE
Montreal-forced-aligner (MFA) model

### ISSUE THREAD

**Issue by fish0510** [RickyL-2000/ROSVOT#2]
Hello,

In your paper, you said you use the Montreal forced aligner (MFA) tool to get word boundaries to guide the model for the better result.
Could you please provide the pre-trained MFA model used for the experiments in Table 3, along with the corresponding MFA version and usage instructions needed to use it?

I would greatly appreciate it if you could!

**Comment by RickyL-2000** [comment]
Hi, We are still working on this part of the code and may release it in the future. However, it is important to note that **MFA works very poorly when handling singing voices**. If you just want to replicate our results, you only need to use M4Singer to train MFA v2.0, and the results won't be too bad. Moreover, we do not intend to use the results of MFA to achieve better outcomes; rather, word-note alignment is always necessary during the annotation process. So, why not provide alignment information directly when extracting MIDI? That's the original purpose.

**Comment by fish0510** [comment]
Thank you for your response. 
I have the same experience with you while using MFA in singing voices.

I would like to confirm that for all the experiments in Table 3, annotated word boundaries were provided to the model for all three datasets, correct?

Additionally, regarding the last two rows in Table 1 (M (w/ E_W) and M (ours)), the difference is that the former uses a word boundary encoder to obtain word boundary information, while the latter directly uses the annotated word boundary information, correct?

Because I am looking for a method to automatically align lyrics with singing voice, I am also curious about your E_W results. Do you have any research related to this?

Thank you for patiently reading my questions. I look forward to your response.

**Comment by RickyL-2000** [comment]
Thank you for your attention.

> I would like to confirm that for all the experiments in Table 3, annotated word boundaries were provided to the model for all three datasets, correct?

Yes, the word boundaries are given in advance to save the cost of post-alignment. Some of them are manually annotated (M4Singer and D1) and some are generated using MFA (OpenSinger and D2).

> Additionally, regarding the last two rows in Table 1 (M (w/ E_W) and M (ours)), the difference is that the former uses a word boundary encoder to obtain word boundary information, while the latter directly uses the annotated word boundary information, correct?

Yes.

> Because I am looking for a method to automatically align lyrics with singing voice, I am also curious about your E_W results. Do you have any research related to this?

The choice of using an additional E_W is clearly suboptimal in a MIDI extraction method, which could be further improved in the next version. The results of E_W are just okay; they are usable. However, E_W does not accept any phoneme conditions. It may only infer word boundaries through intonation, pauses, and rhythm, which is not quite accurate.

Indeed, a special MFA for singing voices is definitely necessary. Right now I only have some ideas about this, but I haven't had the chance to implement them yet. I guess using neural networks and solving this like a dynamic programming problem could be pretty easy, hopefully much better than MFA.
