### ISSUE TITLE
Inference with Python

### ISSUE THREAD

**Issue by shockless** [RickyL-2000/ROSVOT#3]
Hi there! Is there any chance that i can infer the model using RosvotInfer() and not via cmd?

**Comment by RickyL-2000** [comment]
Sure. RosvotInfer() basically takes a `argparse.Namespace()` object as input and configuration. You can cancel argparse and transfer the namespace by other means. 

Or, do you mean using RosvotInfer() like an API or plugin? I need to know your specific needs.

**Comment by shockless** [comment]
I've faced with troubles about imports, as now in the original code it works only from root folder of ROSVOT, however after several caught exceptions, i managed to fix that one. Now it works pretty well. One more thing is that every .run() it initializes models, so i moved that step to the __init__ method.

**Comment by RickyL-2000** [comment]
Good advice, I will consider improving this part.

**Comment by shockless** [comment]
what is more, i get some NoneType errors when checking for slurs. Did you have any of that problems? If so, i would like to talks with you about fixing that part, maybe dialing a call in discord ;)

**Comment by RickyL-2000** [comment]
What kind of errors? Can you provide some sort of log outputs or cases?

**Comment by RickyL-2000** [comment]
OK, I just updated the code and hopefully fixed the bug. The NoneType output is now controlled. However, I believe the source of this bug is the invalid note interval, which is also fixed now.

**Comment by RickyL-2000** [comment]
> what is more, i get some NoneType errors when checking for slurs. Did you have any of that problems? If so, i would like to talks with you about fixing that part, maybe dialing a call in discord ;)

Well I guess we're good here, I'm going to close this issue.
