### ISSUE TITLE
ETA on version 2.0

### ISSUE THREAD

**Issue by dutchsing009** [RickyL-2000/ROSVOT#8]
Hey amazing project here , I wanted to ask if there is going to be 2.0 any time soon?

**Comment by RickyL-2000** [comment]
Thank you for your attention! Yes, 2.0 is currently in development and will include some amazing new features. However, we are currently short-handed (I'm quite busy), it will take some time before it is ready for release.

**Comment by dutchsing009** [comment]
While we are at it , I wanted to ask a quick question , Can ROSVOT Get the  "phoneme sequence | MIDI sequence | MIDI duration sequence | phoneme duration sequence | is slur sequence" or is this one of the new features. I'm asking this because as you know applying the music score is the hardest thing in SVS , probably one of the reasons why there is few SVS papers during the last 3 years. if we can accurately and automatically label datasets as accurate as opencpop and in few hours , it is gonna be revolutionary
if it can do something like that "2002000043|啊|f eng k uang SP|rest|0|0.16178 0.44742 0.11219 2.02505 3.05888|0"
it would be really amazing.

**Comment by dutchsing009** [comment]
labeling is super hard that it probably pushed the top tier researchers to use diffusion transformers(suno,udio) to solve this and just treat vocals as a normal text like in "text-to-speech" by just scraping millions of music data from spotify etc and training it on couple of thousands of H100s and letting scale solve the relationship between text and singing vocals which is in our case called the music score. I still believe that if music score is solved by projects like ROSVOT it would offer way better controllability than stuff like suno and udio.

**Comment by RickyL-2000** [comment]
> While we are at it , I wanted to ask a quick question , Can ROSVOT Get the "phoneme sequence | MIDI sequence | MIDI duration sequence | phoneme duration sequence | is slur sequence" or is this one of the new features. I'm asking this because as you know applying the music score is the hardest thing in SVS , probably one of the reasons why there is few SVS papers during the last 3 years. if we can accurately and automatically label datasets as accurate as opencpop and in few hours , it is gonna be revolutionary if it can do something like that "2002000043|啊|f eng k uang SP|rest|0|0.16178 0.44742 0.11219 2.02505 3.05888|0" it would be really amazing.

Thank you for your attention. If I understand you right, you hope that version 2.0 could accomplish the following things simultaneously: 1) ASR; 2) G2P; 3) MIDI extraction; 4) text-MIDI alignment. Unfortunately, I believe that version 2.0 will not be able to achieve such comprehensiveness. ROSOVOT is designed to focus on MIDI extraction, so the ASR side is handled by other tools such as Whisper. So if you already acquired phonemes and their duration information, ROSOVOT can do the MIDI extraction and text-MIDI alignment (just input phonemes as if they are "words" in the model). 

However, I think you might be on to something, that instead of completely following the input text duration, ROSOVOT can optimize it during the alignment. I can add that to the TODO list.

I can reveal some other potential new features for version 2.0, or rather, some goals I aim to achieve. The current architecture is overly complex for MIDI extraction, modules such as F0 are unnecessary. Also, the word boundary predictor is redundant. I also want to involve reverberation handling, harmony handling, and other MIDI-specific functions. I also want to refactor the code base. However, since we are currently short-handed, it might take some time to complete. (Perhaps I could accept public pull request?)

**Comment by dutchsing009** [comment]
> Thank you for your attention. If I understand you right, you hope that version 2.0 could accomplish the following things simultaneously: 1) ASR; 2) G2P; 3) MIDI extraction; 4) text-MIDI alignment. Unfortunately, I believe that version 2.0 will not be able to achieve such comprehensiveness. ROSOVOT is designed to focus on MIDI extraction, so the ASR side is handled by other tools such as Whisper. So if you already acquired phonemes and their duration information, ROSOVOT can do the MIDI extraction and text-MIDI alignment (just input phonemes as if they are "words" in the model).
> 
Exactly this is what I meant I want ROSVOT to help formatting Singing dataset automatically and make it as accurate as `Opencpop` , But it is totally ok If it can't get the `"phoneme sequence |phoneme duration sequence"` I can maybe try `SOFA` for this.  My question is, Can ROSVOT get the `"MIDI sequence | MIDI duration sequence |"` correctly ? This would be a dream
Or is this only will happen in `version 2.0`? because when i use it , It just outputs a .mid file with the midi inside of it.

**Comment by RickyL-2000** [comment]
> Exactly this is what I meant I want ROSVOT to help formatting Singing dataset automatically and make it as accurate as `Opencpop` , But it is totally ok If it can't get the `"phoneme sequence |phoneme duration sequence"` I can maybe try `SOFA` for this. My question is, Can ROSVOT get the `"MIDI sequence | MIDI duration sequence |"` correctly ? This would be a dream Or is this only will happen in `version 2.0`? because when i use it , It just outputs a .mid file with the midi inside of it.

Ok so that's your question, and sure, it has already been done in the current version. A .npy file will be saved in the save_dir/npy/ directory if everything goes well, where an accurate annotation sequence is saved. In fact, this is the really important file when annotating some datasets, the .mid file is just for human listening. Feel free to load it and check. Or you don't have this file after inference? That could be a problem, and please tell me in that case. 

To check the .npy file, you can use the following code:

```python
note_path = 'path/to/the/npy/file'
item = np.load(note_path, allow_pickle=True).item()
print(item)
```

**Comment by dutchsing009** [comment]
the npy file is there but look they look weird from the inside
![Screenshot 2024-11-22 155044](https://github.com/user-attachments/assets/fbce1199-a117-4bfb-b4b6-42ced8867a4c)
![Screenshot 2024-11-22 155512](https://github.com/user-attachments/assets/ce99ec25-6163-42be-9555-a6ebd5b87055)
And these are the `2 .npy` files and the .midi file too https://gofile.io/d/ZVZK61

**Comment by RickyL-2000** [comment]
That is very weird, it seems the file is corrupted. Let me check later.

**Comment by dutchsing009** [comment]
yeah , also it is an english singing wav , completely unseen

**Comment by RickyL-2000** [comment]
Just to make sure that this is a problem related to np.save(), could you replace the line [here](https://github.com/RickyL-2000/ROSVOT/blob/3c8332bf43adae35f6e4d64971862f2f6139b310/inference/rosvot.py#L409) with the following code?

```python
# old
# np.save(safe_path(f'{self.work_dir}/npy/[note]{fn}.npy'), out, allow_pickle=True)
# new
with open(safe_path(f'{self.work_dir}/npy/[note]{fn}.json'), 'w') as f:
    json.dump(out, f, indent=2)
```

This new code basically switch the .npy file to .json (if I wrote correctly). Hopefully the format is right this time.

**Comment by RickyL-2000** [comment]
Also, try deleting the save_dir before running inference again? I'm afraid it's an overriding issue.

**Comment by dutchsing009** [comment]
![Screenshot 2024-11-22 172829](https://github.com/user-attachments/assets/7be5a90a-7de6-4cf5-bfaf-88a4802c06e5)
it worked!! the output was this 
[[note]output.json](https://github.com/user-attachments/files/17872414/note.output.json)
but the other `notes.npy` is still unreadable which i think is ok now atleast

**Comment by RickyL-2000** [comment]
The notes.npy is merely a summarized version of all results. To change it into a .json file, simply revise [this line](https://github.com/RickyL-2000/ROSVOT/blob/3c8332bf43adae35f6e4d64971862f2f6139b310/inference/rosvot.py#L457C13-L457C83) into the following code:

```python
# old
# np.save(safe_path(f'{self.work_dir}/notes.npy'), d, allow_pickle=True)
# new
with open(safe_path(f'{self.work_dir}/notes.json'), 'w') as f:
    json.dump(d, f, indent=2)
```

Although I don't know why .npy is corrupted, but .json seems to be a viable option for now.

**Comment by dutchsing009** [comment]
No problems we will see in the future , btw the `pitches` part is basically the `MIDI sequence` but in its numeric representation right?? in datasets like OpenCpop they represent it in its letter representation like the following `"2002000043|疯狂|f eng k uang SP|D#4/Eb4 D#4/Eb4 D4 D4 rest|0.609200 0.609200 2.137240 2.137240 3.058880|0.16178 0.44742 0.11219 2.02505 3.05888|0 0 0 0 0"`  Having `D#4/Eb4 D#4/Eb4 D4 D4 rest` AS the midi sequence

Edit: that's why I made a little script that converts numeric to letter , I hope the logic is right in my script 
https://gist.github.com/dutchsing009/1ee329603068bf863c180cf154eb1348

**Comment by RickyL-2000** [comment]
Yes, the mapping from MIDI note numbers to note names can be easily made. For reference, see https://inspiredacoustics.com/en/MIDI_note_numbers_and_center_frequencies

**Comment by dutchsing009** [comment]
ok, Thank you for everything💖 . I hope ROSVOT 2.0 gets a little bit better in English , I know that ROSVOT is only trained on M4Singer which is a chinese singing dataset , But the thing is , it is hard to find an actual good english singing dataset that has natural human labeled annotations , So i hope that the new tweaks that you will introduce work well for English.
