### ISSUE TITLE
如何 eval

### ISSUE THREAD

**Issue by daiw10** [RickyL-2000/ROSVOT#9]
你好 readme 没有看到 eval 的方法，方便补充一下么

**Comment by RickyL-2000** [comment]
evaluation 的方法被集成在了 task 中，而非 inference，需要有 eval dataset，其制作方式和训练集一样。参考 eval 命令：

```shell
CUDA_VISIBLE_DEVICES=0 python tasks/run.py --exp_name <your-exp-name-or-ckpt-name> --infer --hparams "load_ckpt=<path-to-the-ckpt>"
```

evaluation 相关代码在[这里](https://github.com/RickyL-2000/ROSVOT/blob/3c8332bf43adae35f6e4d64971862f2f6139b310/tasks/rosvot/task.py#L376)
